// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SetInterval(arg1) {
  return window['go']['main']['App']['SetInterval'](arg1);
}

export function StartPreventLock() {
  return window['go']['main']['App']['StartPreventLock']();
}

export function StopPreventLock() {
  return window['go']['main']['App']['StopPreventLock']();
}
