// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelShutdownTimer():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function SetInterval(arg1:number):Promise<string>;

export function SetShutdownTime(arg1:number):Promise<string>;

export function StartPreventLock():Promise<string>;

export function StartShutdownTimer():Promise<string>;

export function StopPreventLock():Promise<string>;
